# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'RxSwiftTest' do
  pod 'SnapKit'
  pod 'RxSwift', '~> 4.5'
  pod 'RxCocoa', '~> 4.5'
end
